apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    purpose: multicontainer
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]   # ✅ properly indented under this container